### ISSUE TITLE
Caches.fetch support

### ISSUE THREAD

**Issue by fbjork** [zackehh/cachex#111]
Any plans on adding `fetch` support to Cachex?

From what I can tell you could achieve it using fallbacks, but it's more verbose as you have to add the `set` explicitly. 

Fetch would be a nice shorthand.

**Comment by zackehh** [comment]
@fbjork what exactly do you mean by `fetch`?

**Comment by fbjork** [comment]
Fetch as in get or store if it's a miss

**Comment by zackehh** [comment]
@fbjork that's exactly what fallbacks do :) they'll set automatically if missing based on the return value.

**Comment by fbjork** [comment]
Oh, that wasn't obvious to me!

**Comment by jung-hunsoo** [comment]
It would be great if cachex is providing a "fetch" shorthand function.

We can of course Find -> Update if found -> Insert if missing, but intelligent user-friendly DB products are providing UPSERT functions as well. UPSERT is not only useful for beginners but experienced developers too.

I think that the tools should be primarily focused on usage which yields better productivity and maintenance.

**Comment by whitfin** [comment]
@fbjork FYI; I'm making this more explicit as `fetch` in v3 :)

**Comment by jung-hunsoo** [comment]
I also was confused by the fetch and fallbacks. Though I made it to use fallback, as we know, `fetch` is more generally used for specific representations.

I'm so glad that the author is going to reflect the `fetch`, since it will eliminate confusions and invisible barrier (which is so important to wide-spreading elixir environment as well) and productivity.

Cachex is one of essentials among my apps. Thanks.
