### ISSUE TITLE
Automatic discovery of nodes

### ISSUE THREAD

**Issue by tlvenn** [zackehh/cachex#79]
Hi,

First of all, thanks for this amazing project !

I was wondering if we could not discover nodes automatically using Phoenix Presence which also solves Service Discovery across nodes.

**Comment by zackehh** [comment]
@tlvenn distribution has actually been removed in the 2.x branch because it was flakey. Can Phoenix Presence be using without depending on the entire Phoenix framework?

**Comment by tlvenn** [comment]
Yes, only need Phoenix.PubSub project: https://github.com/phoenixframework/phoenix_pubsub and it is rock solid.

**Comment by tlvenn** [comment]
Ha oky, I wasnt aware of that..

**Comment by tlvenn** [comment]
Could the distribution be added just using hooks with some kind of plugin system so that we could add cachex.distributed package to provide the feature without forking the whole project ?

**Comment by zackehh** [comment]
@tlvenn it only happened recently, see discussion inside #49. 

And per your suggestion, that is something I've tried to figure out. My intent for a while was to have interchangeable backends for a cache, so it could be ETS, could be Mnesia, could be Redis, etc. 

This *would* work, but the big catch is that there are some features which simply do not work in a distributed state. It could be that this repo lives on as a distributed cache implementation and I fork out the non-distributed version into a new repo (which actually makes a fair bit of sense now I think about it). 

How familiar are you with Presence? Do you know if it's possible to have a "master" node? This is the only thing I need to keep distribution - if there's a master node it's trivial to implement things that are currently local-only (i.e. LRW caches) because all the cleanup processes would happen on the master and just replicate out - as it stands there's no way to determine this and so it becomes near impossible to implement correctly.

**Comment by zackehh** [comment]
@tlvenn FWIW I'm looking into Presence - doesn't seem like a good fit just because the sync interval is so high (default is recommended to be 1500ms)

**Comment by zackehh** [comment]
@tlvenn I'm going to close this because of the distribution being stripped out. I'm planning on building up a new project aimed at being a distributed implementation in future so I'll drop a link here when that's up.

Cachex being distributed really doesn't make much sense due to the consistency issues as well as trying to be fast. My intent is to build something which is distributed at its core to improve the resiliency there.

If you have any other suggestions please feel free to let me know, but for now it looks like distribution is dying in the v1.x branch.

**Comment by tlvenn** [comment]
No problem @zackehh, thanks for the discussion.
