### ISSUE TITLE
Options in Cachex.get are not propagated to set when result is fetched using fallback

### ISSUE THREAD

**Issue by burmajam** [zackehh/cachex#86]
Cachex version: 1.2.2

Problem:
- You can't override :ttl for example in Cachex.get/3 with fallback.

Solution:
- https://github.com/zackehh/cachex/compare/v1.2.2...burmajam:fix/v1.2.2

**Comment by zackehh** [comment]
I actually left that on purpose, because I felt it would be better to explicitly add a TTL there afterwards. 

Can you please target master with the change, document it, and also do the same to `get_and_update/4`?

**Comment by zackehh** [comment]
I remembered why I originally never added this;

I believe that if we add it to `get/3`, people will then assume that it works with `incr/4` and an initial value (where it can't actually work due to the performance hit of ~10x).

It's because of this that I added the `:loaded` tag, so you can do something like this:

```elixir
retrieved_value = Cachex.execute(:my_cache, fn(state) ->
  get_result = Cachex.get(state, "key")

  if match?({ :loaded, _val }, get_result) do
    Cachex.expire(state, "key", 5000)
  end

  get_result
end)
```

This has little overhead and ensures that your keys always have the right TTL. The distinct advantage here is that we're not blending options (e.g. what if there's a common option between `get/3` and `set/4`?). The other is that it's more natural in the case of `incr` and `decr`, which also have the same semantics just via the `:missing` tag.

@burmajam does this work for you? I don't believe passing the options through at this point is a good idea - unless we pull out only `set/4` specific options, which is an extra overhead we don't want. 

I appreciate your PR, and if you have any further opinions/questions, please feel free to share them!

**Comment by burmajam** [comment]
Hi @zackehh,

Thank you for quick response. It wasn't obvious for me that options are not proxied, so I would suggest only to update documentation with this note and solution that works great btw :)

**Comment by zackehh** [comment]
I'll add a note to the docs about not being passed through!
