### ISSUE TITLE
Feature request: Add an option to broadcast purged records

### ISSUE THREAD

**Issue by bopjesvla** [zackehh/cachex#98]
Currently, the Janitor only emits the eviction count.

Use case: a scheduler for simple, cancelable named jobs.

**Comment by zackehh** [comment]
@bopjesvla could you clarify a little bit more on your use case? What do you mean by broadcasting purged records?

**Comment by bopjesvla** [comment]
My use case was needlessly specific, I guess. The point is that I'd like to do something with a record once it's expired. The simplest way to do this is to broadcast all deleted records to the hooks. Since this causes significant overhead, this should be an optional feature.

If this still isn't clear, I'll just send a PR.

**Comment by zackehh** [comment]
Aloha @bopjesvla.

There are a few reasons why this is not going to make it in (in the way you want it).

The first, as you have already pointed out, is the overhead of doing what you're asking for. There are many people using Cachex in production which is purging tens of thousands of records in each Janitor sweep. Naturally this means that it has to be hidden behind configuration as you stated, but that leads to another issue.

The Janitor operates on an ETS level to efficiently remove documents at extreme speeds - if the Janitor had to load these documents back before removing them, there are a number of potential issues:

- Memory use: obviously if you have to evict a whole bunch of records, you're going to sap on memory pretty badly.
- Slowness: reading each document back, broadcasting it, then evicting it is going to be **horribly** slow.
- Inconsistency: what happens if you read a document back, and then once you come to evict it, it has actually been written again by another process in the meantime? You lose the atomicity.

In curious if your use case actually requires the use of a Janitor process, or if you could live with on-demand expiration? There may be something we can do with regards to ODE for notifications in this way.

**Comment by bopjesvla** [comment]
The first two issues only come into play if you evict very large numbers every second. As for the last point, in my case a full cache lock would not be an issue, but I've realized that my requirements are so abnormal that I should just roll my own Janitor. Thanks for hearing me out!

**Comment by zackehh** [comment]
@bopjesvla No problem, perhaps gist your own Janitor here and perhaps I can come up with a way where you can plug your own in easily? No promises though :p
